### ISSUE TITLE
Invalid JSON on auto generated dashboard

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash_client#34]
This dashboard:

3) Recommended Highlights: https://sql.telemetry.mozilla.org/public/dashboards/5y1PAGTeDWNaKNCS5WKe3GSjQzPp9NkDIQuIkaux?org_slug=default 

is complaining about invalid JSON.

**Comment by jaredkerim** [comment]
Another one:

https://sql.telemetry.mozilla.org/public/dashboards/cCGhHa60ukkGVEAJA2ATSSJruW9xJ9yyX1pgUIbk?org_slug=default

**Comment by jaredkerim** [comment]
This one too:

17) Weighted highlights: https://sql.telemetry.mozilla.org/public/dashboards/ArFazsBGyejFzL6ofoZfH7OnfaWg5H3EYOjtbZkM?org_slug=default

**Comment by emtwo** [comment]
Resolved with commit: f64929764858e77bb5a41fb08baeba0e2c8342aa. The next time the job runs, it should fix these.
