### ISSUE TITLE
Split Statistical Analysis into separate tables for New/Existing Users

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash_client#52]
Rather than having a single section called 'Statistical Analysis' with both 'Existing Users' and 'New Users' metrics differences in a single table, can we split it into two sections, one just for Existing Users and one for New Users so it's easier to read.

<img width="1399" alt="screenshot 2017-10-16 13 17 21" src="https://user-images.githubusercontent.com/119884/31625570-77721294-b274-11e7-9252-588d751b995a.png">

**Comment by jaredkerim** [comment]
We shoudl also make it so when you create a dashboard you specify whether you want a) existing users b) new users c) both and it shoudl only include the graphs/stats tables for the groups selected.

**Comment by emtwo** [comment]
This was mostly resolved in issue #54. The remaining work entails 2 parts:

1) The query templates for new and existing users should be separated.
2) Create two separate ttest tables, one with each template.
